# hot scroll image
###
GET {{host}}/banners?icode={{iCode}} HTTP/1.1

# scroll tab
###
GET {{host}}/tabs?icode={{iCode}} HTTP/1.1

# slide image
###
GET {{host}}/channels?icode={{iCode}} HTTP/1.1

###
GET {{host}}/tab-menu?icode={{iCode}} HTTP/1.1