# hot scroll image
###
GET {{host}}/banners?icode={{iCode}} HTTP/1.1

# scroll tab
###
GET {{host}}/tabs?icode={{iCode}} HTTP/1.1

# slide image
###
GET {{host}}/channels?icode={{iCode}} HTTP/1.1

###
GET {{host}}/tabMenu?icode={{iCode}} HTTP/1.1

###
GET {{host}}/ads?categories_like=fruit&icode={{iCode}} HTTP/1.1

###
GET {{host}}/products?categories_like=fruit&icode={{iCode}} HTTP/1.1

###
GET {{host}}/productVariants?_expand=product&_embed=productVariantImages&productId=1&icode={{iCode}} HTTP/1.1

###
GET {{host}}/profile?icode={{iCode}} HTTP/1.1

